export const AIRPORTS = [
  // Domestic Bangladesh
  { code: 'DAC', name: 'Hazrat Shahjalal International Airport', city: 'Dhaka', country: 'Bangladesh', type: 'Domestic' },
  { code: 'CGP', name: 'Shah Amanat International Airport', city: 'Chittagong', country: 'Bangladesh', type: 'Domestic' },
  { code: 'ZYL', name: 'Osmani International Airport', city: 'Sylhet', country: 'Bangladesh', type: 'Domestic' },
  { code: 'CXB', name: 'Cox\'s Bazar Airport', city: 'Cox\'s Bazar', country: 'Bangladesh', type: 'Domestic' },
  { code: 'JSR', name: 'Jessore Airport', city: 'Jessore', country: 'Bangladesh', type: 'Domestic' },
  { code: 'BZL', name: 'Barisal Airport', city: 'Barisal', country: 'Bangladesh', type: 'Domestic' },
  { code: 'SPD', name: 'Saidpur Airport', city: 'Saidpur', country: 'Bangladesh', type: 'Domestic' },
  { code: 'RJH', name: 'Shah Makhdum Airport', city: 'Rajshahi', country: 'Bangladesh', type: 'Domestic' },
  { code: 'IRD', name: 'Ishurdi Airport', city: 'Ishurdi', country: 'Bangladesh', type: 'Domestic' },

  // International - Middle East
  { code: 'DXB', name: 'Dubai International Airport', city: 'Dubai', country: 'UAE', type: 'International' },
  { code: 'AUH', name: 'Abu Dhabi International Airport', city: 'Abu Dhabi', country: 'UAE', type: 'International' },
  { code: 'DOH', name: 'Hamad International Airport', city: 'Doha', country: 'Qatar', type: 'International' },
  { code: 'JED', name: 'King Abdulaziz International Airport', city: 'Jeddah', country: 'Saudi Arabia', type: 'International' },
  { code: 'RUH', name: 'King Khalid International Airport', city: 'Riyadh', country: 'Saudi Arabia', type: 'International' },
  { code: 'MED', name: 'Prince Mohammad bin Abdulaziz Airport', city: 'Medina', country: 'Saudi Arabia', type: 'International' },
  { code: 'MCT', name: 'Muscat International Airport', city: 'Muscat', country: 'Oman', type: 'International' },
  { code: 'KWI', name: 'Kuwait International Airport', city: 'Kuwait City', country: 'Kuwait', type: 'International' },
  { code: 'BAH', name: 'Bahrain International Airport', city: 'Manama', country: 'Bahrain', type: 'International' },
  { code: 'SHJ', name: 'Sharjah International Airport', city: 'Sharjah', country: 'UAE', type: 'International' },
  { code: 'AMM', name: 'Queen Alia International Airport', city: 'Amman', country: 'Jordan', type: 'International' },

  // International - Asia & Pacific
  { code: 'SIN', name: 'Changi Airport', city: 'Singapore', country: 'Singapore', type: 'International' },
  { code: 'BKK', name: 'Suvarnabhumi Airport', city: 'Bangkok', country: 'Thailand', type: 'International' },
  { code: 'KUL', name: 'Kuala Lumpur International Airport', city: 'Kuala Lumpur', country: 'Malaysia', type: 'International' },
  { code: 'HKG', name: 'Hong Kong International Airport', city: 'Hong Kong', country: 'China', type: 'International' },
  { code: 'ICN', name: 'Incheon International Airport', city: 'Seoul', country: 'South Korea', type: 'International' },
  { code: 'NRT', name: 'Narita International Airport', city: 'Tokyo', country: 'Japan', type: 'International' },
  { code: 'HND', name: 'Haneda Airport', city: 'Tokyo', country: 'Japan', type: 'International' },
  { code: 'CAN', name: 'Guangzhou Baiyun International Airport', city: 'Guangzhou', country: 'China', type: 'International' },
  { code: 'PVG', name: 'Shanghai Pudong International Airport', city: 'Shanghai', country: 'China', type: 'International' },
  { code: 'PEK', name: 'Beijing Capital International Airport', city: 'Beijing', country: 'China', type: 'International' },
  { code: 'MNL', name: 'Ninoy Aquino International Airport', city: 'Manila', country: 'Philippines', type: 'International' },
  { code: 'CGK', name: 'Soekarno-Hatta International Airport', city: 'Jakarta', country: 'Indonesia', type: 'International' },
  { code: 'DPS', name: 'Ngurah Rai International Airport', city: 'Bali', country: 'Indonesia', type: 'International' },
  { code: 'SGN', name: 'Tan Son Nhat International Airport', city: 'Ho Chi Minh City', country: 'Vietnam', type: 'International' },
  { code: 'HAN', name: 'Noi Bai International Airport', city: 'Hanoi', country: 'Vietnam', type: 'International' },
  { code: 'CMB', name: 'Bandaranaike International Airport', city: 'Colombo', country: 'Sri Lanka', type: 'International' },
  { code: 'KTM', name: 'Tribhuvan International Airport', city: 'Kathmandu', country: 'Nepal', type: 'International' },
  { code: 'MLE', name: 'Velana International Airport', city: 'Male', country: 'Maldives', type: 'International' },
  { code: 'SYD', name: 'Sydney Airport', city: 'Sydney', country: 'Australia', type: 'International' },
  { code: 'MEL', name: 'Melbourne Airport', city: 'Melbourne', country: 'Australia', type: 'International' },
  { code: 'AKL', name: 'Auckland Airport', city: 'Auckland', country: 'New Zealand', type: 'International' },

  // International - India
  { code: 'DEL', name: 'Indira Gandhi International Airport', city: 'Delhi', country: 'India', type: 'International' },
  { code: 'CCU', name: 'Netaji Subhash Chandra Bose International Airport', city: 'Kolkata', country: 'India', type: 'International' },
  { code: 'BOM', name: 'Chhatrapati Shivaji Maharaj International Airport', city: 'Mumbai', country: 'India', type: 'International' },
  { code: 'MAA', name: 'Chennai International Airport', city: 'Chennai', country: 'India', type: 'International' },
  { code: 'BLR', name: 'Kempegowda International Airport', city: 'Bangalore', country: 'India', type: 'International' },
  { code: 'HYD', name: 'Rajiv Gandhi International Airport', city: 'Hyderabad', country: 'India', type: 'International' },

  // International - Europe
  { code: 'LHR', name: 'London Heathrow Airport', city: 'London', country: 'UK', type: 'International' },
  { code: 'LGW', name: 'London Gatwick Airport', city: 'London', country: 'UK', type: 'International' },
  { code: 'CDG', name: 'Charles de Gaulle Airport', city: 'Paris', country: 'France', type: 'International' },
  { code: 'FRA', name: 'Frankfurt Airport', city: 'Frankfurt', country: 'Germany', type: 'International' },
  { code: 'AMS', name: 'Amsterdam Airport Schiphol', city: 'Amsterdam', country: 'Netherlands', type: 'International' },
  { code: 'IST', name: 'Istanbul Airport', city: 'Istanbul', country: 'Turkey', type: 'International' },
  { code: 'FCO', name: 'Leonardo da Vinci–Fiumicino Airport', city: 'Rome', country: 'Italy', type: 'International' },
  { code: 'MAD', name: 'Adolfo Suárez Madrid–Barajas Airport', city: 'Madrid', country: 'Spain', type: 'International' },
  { code: 'ZRH', name: 'Zurich Airport', city: 'Zurich', country: 'Switzerland', type: 'International' },
  { code: 'CPH', name: 'Copenhagen Airport', city: 'Copenhagen', country: 'Denmark', type: 'International' },
  { code: 'VIE', name: 'Vienna International Airport', city: 'Vienna', country: 'Austria', type: 'International' },
  { code: 'BRU', name: 'Brussels Airport', city: 'Brussels', country: 'Belgium', type: 'International' },

  // International - Americas
  { code: 'JFK', name: 'John F. Kennedy International Airport', city: 'New York', country: 'USA', type: 'International' },
  { code: 'EWR', name: 'Newark Liberty International Airport', city: 'Newark', country: 'USA', type: 'International' },
  { code: 'LAX', name: 'Los Angeles International Airport', city: 'Los Angeles', country: 'USA', type: 'International' },
  { code: 'SFO', name: 'San Francisco International Airport', city: 'San Francisco', country: 'USA', type: 'International' },
  { code: 'ORD', name: 'O\'Hare International Airport', city: 'Chicago', country: 'USA', type: 'International' },
  { code: 'YYZ', name: 'Toronto Pearson International Airport', city: 'Toronto', country: 'Canada', type: 'International' },
  { code: 'YVR', name: 'Vancouver International Airport', city: 'Vancouver', country: 'Canada', type: 'International' },
  { code: 'IAD', name: 'Washington Dulles International Airport', city: 'Washington D.C.', country: 'USA', type: 'International' },
  { code: 'MIA', name: 'Miami International Airport', city: 'Miami', country: 'USA', type: 'International' },
  { code: 'DFW', name: 'Dallas/Fort Worth International Airport', city: 'Dallas', country: 'USA', type: 'International' },
  { code: 'ATL', name: 'Hartsfield–Jackson Atlanta International Airport', city: 'Atlanta', country: 'USA', type: 'International' },

  // International - Africa
  { code: 'CAI', name: 'Cairo International Airport', city: 'Cairo', country: 'Egypt', type: 'International' },
  { code: 'JNB', name: 'O. R. Tambo International Airport', city: 'Johannesburg', country: 'South Africa', type: 'International' },
  { code: 'CPT', name: 'Cape Town International Airport', city: 'Cape Town', country: 'South Africa', type: 'International' },
  { code: 'ADD', name: 'Addis Ababa Bole International Airport', city: 'Addis Ababa', country: 'Ethiopia', type: 'International' },
  { code: 'NBO', name: 'Jomo Kenyatta International Airport', city: 'Nairobi', country: 'Kenya', type: 'International' },
];
